# Generated by Django 2.0.10 on 2019-02-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20190207_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='still',
            name='videoID',
            field=models.TextField(blank=True, null=True, verbose_name='ID do Vídeo'),
        ),
    ]
