# Generated by Django 2.0.10 on 2019-02-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_still_videoid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='still',
            name='videoID',
        ),
        migrations.AddField(
            model_name='still',
            name='thumbnail',
            field=models.TextField(blank=True, null=True, verbose_name='Link da Thumbnail'),
        ),
    ]
