# Generated by Django 2.0.10 on 2019-02-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20190221_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='still',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Link do Vídeo'),
        ),
        migrations.AlterField(
            model_name='still',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Link da Thumbnail'),
        ),
    ]
