# Generated by Django 2.0.10 on 2019-04-30 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20190221_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='still',
            name='thumbnail',
        ),
    ]
